package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/comment-hq/comment-cli/internal/commentbus"
)

// Docker-mode installs (the "Run in a Docker Image" option on <baseUrl>/setup,
// generated by dockerAgentInstallLines in agent-docs.ts) run the daemon + agent
// runtimes inside a container instead of as a host launchd/systemd service. They
// leave behind, per origin:
//   - a container named comment-agent-<slug> started with --restart unless-stopped
//     (so it keeps running and re-launching across reboots),
//   - named volumes comment-agent-state-<slug> and comment-agent-home-<slug> that
//     hold the daemon pairing plus the agent runtime (Claude/Codex) credentials,
//   - the pulled image (ghcr.io/comment-hq/comment-agent:latest by default on a
//     production origin, or ghcr.io/comment-hq/comment-agent-staging:latest on a
//     staging origin).
//
// `comment uninstall` otherwise only tears down host-side state, so without this
// step a uninstall on a Docker-mode machine would leave a live, credentialed,
// auto-restarting agent container behind. We discover the artifacts by name
// prefix because the install script names everything comment-agent-<slug>.
const (
	dockerAgentResourcePrefix   = "comment-agent-"
	canonicalProductionBaseURL  = "https://comment.io"
	defaultAgentImageRef        = "ghcr.io/comment-hq/comment-agent:latest"
	defaultStagingAgentImageRef = "ghcr.io/comment-hq/comment-agent-staging:latest"
)

// fallbackAgentImageRefs is what `--remove-image` targets when no container is left
// to read the actual image from. It mirrors the install script's image selection
// (agentImageRefForBaseUrl in packages/shared/src/agent-docs.ts):
//   - an explicit COMMENT_IO_AGENT_IMAGE pin wins, exactly as the install used it;
//   - otherwise we can't be certain which package the install pulled — a staging
//     install can FALL BACK to the production image when the staging tag isn't
//     published, and a personal-staging origin can be present while `home` is the
//     production default — so we return BOTH known defaults (the home's env default
//     first). This path only runs when NO agent container exists anywhere, so no
//     live install's image is at risk, and `docker rmi` of a tag that isn't present
//     is a harmless no-op.
func fallbackAgentImageRefs(home string) []string {
	if v := strings.TrimSpace(os.Getenv("COMMENT_IO_AGENT_IMAGE")); v != "" {
		return []string{v}
	}
	if environmentForUninstallHome(home).IsStaging() {
		return []string{defaultStagingAgentImageRef, defaultAgentImageRef}
	}
	return []string{defaultAgentImageRef, defaultStagingAgentImageRef}
}

var (
	dockerSlugSchemeRE   = regexp.MustCompile(`^https?://`)
	dockerSlugNonAlnumRE = regexp.MustCompile(`[^a-zA-Z0-9]+`)
)

// dockerAgentSlug derives the per-origin slug the install script bakes into the
// container/volume names. It MUST stay in lockstep with dockerAgentInstallLines
// in packages/shared/src/agent-docs.ts: strip the scheme, collapse non-alnum runs
// to "-", trim "-", lowercase, and fall back to "default".
func dockerAgentSlug(baseURL string) string {
	s := dockerSlugSchemeRE.ReplaceAllString(baseURL, "")
	s = dockerSlugNonAlnumRE.ReplaceAllString(s, "-")
	s = strings.ToLower(strings.Trim(s, "-"))
	if s == "" {
		return "default"
	}
	return s
}

func dockerAgentContainerName(slug string) string { return dockerAgentResourcePrefix + slug }

// dockerAgentVolumeInfixes are the named-volume kinds the install creates per
// slug: state (/state), home (/home/agent), and projected (/projected-agents, the
// projected plain-agent profiles). MUST stay in lockstep with dockerAgentInstallLines.
var dockerAgentVolumeInfixes = []string{"state-", "home-", "projected-"}

// dockerAgentVolumeNames are the named volumes the install creates for a slug.
func dockerAgentVolumeNames(slug string) []string {
	names := make([]string, len(dockerAgentVolumeInfixes))
	for i, infix := range dockerAgentVolumeInfixes {
		names[i] = dockerAgentResourcePrefix + infix + slug
	}
	return names
}

// slugFromDockerAgentContainer recovers the origin slug from a container name
// (containers are named comment-agent-<slug>; the state/home volumes carry extra
// "state-"/"home-" infixes, but those are never container names).
func slugFromDockerAgentContainer(name string) string {
	return strings.TrimPrefix(name, dockerAgentResourcePrefix)
}

// slugFromDockerAgentVolume recovers the origin slug from a state/home volume name
// (comment-agent-state-<slug> / comment-agent-home-<slug>), so a volume left behind
// after its container was removed still counts as evidence of that origin.
func slugFromDockerAgentVolume(name string) (string, bool) {
	for _, infix := range dockerAgentVolumeInfixes {
		prefix := dockerAgentResourcePrefix + infix
		if strings.HasPrefix(name, prefix) {
			return strings.TrimPrefix(name, prefix), true
		}
	}
	return "", false
}

// environmentForUninstallHome resolves which environment the home being
// uninstalled belongs to. The rest of uninstall is scoped by --home, so the
// Docker slug MUST follow the home too — otherwise `comment uninstall --home
// ~/.comment-io-staging` (without --staging) would remove the home for staging
// but the Docker container/volumes for production. A home matching a default
// per-env dir pins that env; a custom COMMENT_IO_HOME falls back to the process
// environment.
func environmentForUninstallHome(home string) commentbus.Environment {
	clean := filepath.Clean(home)
	for _, name := range []string{commentbus.EnvProduction, commentbus.EnvStaging} {
		env := commentbus.Environment{Name: name}
		if dir, err := env.DefaultHomeDir(); err == nil && filepath.Clean(dir) == clean {
			return env
		}
	}
	return commentbus.CurrentEnvironment()
}

// uninstallDockerEnvSlug is the slug for the environment of the home being
// uninstalled (honoring per-env COMMENT_IO_BASE_URL / COMMENT_IO_STAGING_BASE_URL
// overrides). Used to disambiguate when several origins' agents share one Docker
// daemon.
func uninstallDockerEnvSlug(home string) string {
	return dockerAgentSlug(environmentForUninstallHome(home).DefaultBaseURL())
}

// selectDockerTeardownSlug decides which origin's resources to remove, using the
// containers AND volumes present as origin evidence (the install names resources
// from the /setup origin, which the host keeps no record of):
//   - the active environment's slug, whenever a container OR a leftover volume for
//     it exists (so a half-removed env install is finished, never a foreign one);
//   - otherwise, the sole origin present, when exactly one origin has any footprint
//     (covers personal-staging / custom origins the env default wouldn't match);
//   - otherwise (several origins, none the active env) nothing — slug "" — with all
//     agent containers reported as left in place.
//
// anyContainer distinguishes "nothing installed" from "present but not selected";
// ambiguous marks the several-origins-no-match case (slug ""). The caller computes
// which resources are left in place from the returned slug.
func selectDockerTeardownSlug(containerNames, volumeNames []string, env string) (slug string, anyContainer, ambiguous bool) {
	anyContainer = len(containerNames) > 0
	present := map[string]bool{}
	for _, name := range containerNames {
		present[slugFromDockerAgentContainer(name)] = true
	}
	for _, vol := range volumeNames {
		if s, ok := slugFromDockerAgentVolume(vol); ok {
			present[s] = true
		}
	}

	switch {
	case present[env]:
		return env, anyContainer, false
	case len(present) == 1:
		for s := range present {
			slug = s
		}
		return slug, anyContainer, false
	case len(present) == 0:
		// Truly nothing on the daemon: keep the env slug so the default-image
		// fallback (and "nothing found" messaging) behaves.
		return env, anyContainer, false
	default:
		return "", anyContainer, true
	}
}

// dockerAgentArtifacts is the comment-agent-* Docker resources teardown will act
// on, scoped to a single origin and discovered up front so removal can act on the
// image the container actually uses.
type dockerAgentArtifacts struct {
	Containers []string
	Volumes    []string
	// Images is the image ref the target container was created from. We remove it
	// (with --remove-image) rather than a recomputed default so a custom
	// COMMENT_IO_AGENT_IMAGE install drops the image actually pulled, not :latest.
	Images []string
	// OtherContainers / OtherVolumes are comment-agent resources left in place
	// because they belong to another origin (or, when Ambiguous, every present
	// resource). Reported — not silently skipped — so a user can clean the
	// credential-bearing leftovers deliberately.
	OtherContainers []string
	OtherVolumes    []string
	// AnyContainer is whether any comment-agent container was present at all,
	// distinguishing "nothing installed" from "present but not selected".
	AnyContainer bool
	// Ambiguous marks the several-origins-none-match case: nothing is removed.
	Ambiguous bool
}

// filterCommentAgentNames keeps only comment-agent-* names from newline-delimited
// `docker ...--format` output. We filter in Go rather than via `--filter name=`
// because docker's name filter semantics (substring vs anchored regex) differ
// across container and volume listings and across engine versions.
func filterCommentAgentNames(out []byte) []string {
	var names []string
	for _, line := range strings.Split(string(out), "\n") {
		name := strings.TrimSpace(line)
		if strings.HasPrefix(name, dockerAgentResourcePrefix) {
			names = append(names, name)
		}
	}
	return names
}

// parseDockerAgentContainerImages parses tab-separated "<name>\t<image>" lines
// into a comment-agent-* container name -> image map.
func parseDockerAgentContainerImages(out []byte) map[string]string {
	images := map[string]string{}
	for _, line := range strings.Split(string(out), "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		fields := strings.SplitN(line, "\t", 2)
		name := strings.TrimSpace(fields[0])
		if !strings.HasPrefix(name, dockerAgentResourcePrefix) {
			continue
		}
		image := ""
		if len(fields) == 2 {
			image = strings.TrimSpace(fields[1])
		}
		images[name] = image
	}
	return images
}

// listDockerAgentArtifacts selects a single origin's agent container (with its
// image) and named volumes, scoped so a shared Docker daemon's other-environment
// agents are never touched. `docker ps`/`docker volume ls` fail cleanly when the
// engine is not running, so their error doubles as the engine-reachability signal.
func listDockerAgentArtifacts(ctx context.Context, dockerBin, envSlug string, exact bool) (dockerAgentArtifacts, error) {
	psOut, err := runUninstallCommand(ctx, 15*time.Second, dockerBin, "ps", "-a", "--format", "{{.Names}}\t{{.Image}}")
	if err != nil {
		return dockerAgentArtifacts{}, err
	}
	volOut, err := runUninstallCommand(ctx, 15*time.Second, dockerBin, "volume", "ls", "--format", "{{.Name}}")
	if err != nil {
		return dockerAgentArtifacts{}, err
	}
	containerImages := parseDockerAgentContainerImages(psOut)
	names := make([]string, 0, len(containerImages))
	for name := range containerImages {
		names = append(names, name)
	}
	sort.Strings(names)
	allVolumes := filterCommentAgentNames(volOut)
	sort.Strings(allVolumes)

	slug, anyContainer, ambiguous := selectDockerTeardownSlug(names, allVolumes, envSlug)
	if exact {
		slug, ambiguous = envSlug, false
	}
	artifacts := dockerAgentArtifacts{AnyContainer: anyContainer, Ambiguous: ambiguous}

	// The selected origin's resources (empty target set when slug == "").
	targetContainer := ""
	ourVolumes := map[string]bool{}
	if slug != "" {
		targetContainer = dockerAgentContainerName(slug)
		if image, ok := containerImages[targetContainer]; ok {
			artifacts.Containers = []string{targetContainer}
			if image != "" {
				artifacts.Images = []string{image}
			}
		}
		for _, vol := range dockerAgentVolumeNames(slug) {
			ourVolumes[vol] = true
		}
		for _, vol := range allVolumes {
			if ourVolumes[vol] {
				artifacts.Volumes = append(artifacts.Volumes, vol)
			}
		}
	}

	// Everything else is left in place — reported so credential-bearing leftovers
	// are never silently hidden.
	for _, name := range names {
		if name != targetContainer {
			artifacts.OtherContainers = append(artifacts.OtherContainers, name)
		}
	}
	for _, vol := range allVolumes {
		if !ourVolumes[vol] {
			artifacts.OtherVolumes = append(artifacts.OtherVolumes, vol)
		}
	}
	return artifacts, nil
}

// dockerImagesToRemove returns the images --remove-image should drop: the ref the
// target container used. When no agent container exists anywhere (single-origin
// machine whose container is already gone), fall back to the configured/default
// ref. When other origins' containers are present (ambiguous, or the active
// origin's container was already removed), return nothing rather than risk an
// unrelated image.
func dockerImagesToRemove(artifacts dockerAgentArtifacts, home string) []string {
	if len(artifacts.Images) > 0 {
		return artifacts.Images
	}
	if !artifacts.AnyContainer {
		return fallbackAgentImageRefs(home)
	}
	return nil
}

func dockerRuntimeMarkerHomesForUninstall(home string) []string {
	seen := map[string]bool{}
	var homes []string
	add := func(path string) {
		clean := filepath.Clean(path)
		if clean == "." || seen[clean] {
			return
		}
		seen[clean] = true
		homes = append(homes, clean)
	}
	add(home)
	for _, envName := range []string{commentbus.EnvProduction, commentbus.EnvStaging} {
		if defaultHome, err := (commentbus.Environment{Name: envName}).DefaultHomeDir(); err == nil {
			add(defaultHome)
		}
	}
	return homes
}

func dockerRuntimeMarkerMatchesUninstallTarget(marker dockerRuntimeTarget, target dockerRuntimeTarget) bool {
	if marker.Container != "" && target.Container != "" && marker.Container == target.Container {
		return true
	}
	if marker.BaseURL != "" && target.BaseURL != "" && sameBusPairBaseURL(marker.BaseURL, target.BaseURL) {
		return true
	}
	return false
}

type dockerUninstallTarget struct {
	Target   dockerRuntimeTarget
	Slug     string
	Exact    bool
	Warnings []string
	Blocked  bool
}

func dockerUninstallTargetForHome(home string) dockerUninstallTarget {
	fallback := dockerRuntimeTargetForBaseURL(environmentForUninstallHome(home).DefaultBaseURL())
	paths, err := commentbus.ResolvePaths(home)
	if err == nil {
		if target, ok, readErr := readDockerRuntimeInstallMarker(paths); readErr == nil && ok {
			return dockerUninstallTarget{Target: target, Slug: dockerRuntimeTargetSlug(target, home), Exact: true}
		} else if readErr != nil {
			return dockerUninstallTarget{
				Target:   fallback,
				Slug:     uninstallDockerEnvSlug(home),
				Warnings: []string{dockerRuntimeInstallMarkerPath(paths) + ": " + readErr.Error()},
				Blocked:  true,
			}
		}
	}
	if target, warnings, ok, blocked := dockerRuntimeFallbackMarkerTargetForUninstall(home); blocked {
		return dockerUninstallTarget{Target: fallback, Slug: uninstallDockerEnvSlug(home), Warnings: warnings, Blocked: true}
	} else if ok {
		return dockerUninstallTarget{Target: target, Slug: dockerRuntimeTargetSlug(target, home), Exact: true, Warnings: warnings}
	}
	return dockerUninstallTarget{Target: fallback, Slug: uninstallDockerEnvSlug(home)}
}

func dockerRuntimeTargetSlug(target dockerRuntimeTarget, home string) string {
	if target.Container != "" && strings.HasPrefix(target.Container, dockerAgentResourcePrefix) {
		return slugFromDockerAgentContainer(target.Container)
	}
	if target.BaseURL != "" {
		return dockerAgentSlug(target.BaseURL)
	}
	return uninstallDockerEnvSlug(home)
}

func dockerRuntimeFallbackMarkerTargetForUninstall(home string) (dockerRuntimeTarget, []string, bool, bool) {
	if !dockerRuntimeFallbackMarkersCanApply(home) {
		return dockerRuntimeTarget{}, nil, false, false
	}
	selected := filepath.Clean(home)
	var warnings []string
	var candidates []dockerRuntimeTarget
	for _, markerHome := range dockerRuntimeMarkerHomesForUninstall(home) {
		if filepath.Clean(markerHome) == selected {
			continue
		}
		paths, err := commentbus.ResolvePaths(markerHome)
		if err != nil {
			warnings = append(warnings, markerHome+": "+err.Error())
			continue
		}
		marker, ok, err := readDockerRuntimeInstallMarker(paths)
		if err != nil {
			warnings = append(warnings, dockerRuntimeInstallMarkerPath(paths)+": "+err.Error())
			continue
		}
		if ok && dockerRuntimeFallbackMarkerApplies(home, marker) {
			candidates = append(candidates, marker)
		}
	}
	if len(warnings) > 0 {
		return dockerRuntimeTarget{}, warnings, false, true
	}
	if len(candidates) == 1 {
		return candidates[0], nil, true, false
	}
	return dockerRuntimeTarget{}, nil, false, false
}

func dockerRuntimeFallbackMarkersCanApply(home string) bool {
	stagingHome, err := (commentbus.Environment{Name: commentbus.EnvStaging}).DefaultHomeDir()
	return err == nil && filepath.Clean(home) == filepath.Clean(stagingHome)
}

func dockerRuntimeFallbackMarkerApplies(home string, marker dockerRuntimeTarget) bool {
	if !dockerRuntimeFallbackMarkersCanApply(home) {
		return false
	}
	return marker.BaseURL != "" && !dockerRuntimeMarkerBaseIsProduction(marker.BaseURL)
}

func dockerRuntimeMarkerBaseIsProduction(base string) bool {
	base = strings.TrimRight(strings.TrimSpace(base), "/")
	if sameBusPairBaseURL(base, canonicalProductionBaseURL) {
		return true
	}
	u, err := url.Parse(base)
	if err != nil {
		return false
	}
	host := strings.ToLower(u.Hostname())
	return host == "comment.io" || host == "www.comment.io"
}

func dockerRuntimeMarkersForUninstall(home string, target dockerRuntimeTarget) ([]string, []string) {
	var pathsOut []string
	var warnings []string
	for _, markerHome := range dockerRuntimeMarkerHomesForUninstall(home) {
		paths, err := commentbus.ResolvePaths(markerHome)
		if err != nil {
			warnings = append(warnings, markerHome+": "+err.Error())
			continue
		}
		marker, ok, err := readDockerRuntimeInstallMarker(paths)
		if err != nil {
			warnings = append(warnings, dockerRuntimeInstallMarkerPath(paths)+": "+err.Error())
			continue
		}
		if !ok || !dockerRuntimeMarkerMatchesUninstallTarget(marker, target) {
			continue
		}
		pathsOut = append(pathsOut, dockerRuntimeInstallMarkerPath(paths))
	}
	return pathsOut, warnings
}

func selectedDockerRuntimeMarkerForUninstall(paths commentbus.Paths) (string, bool) {
	path := dockerRuntimeInstallMarkerPath(paths)
	if _, err := os.Lstat(path); err == nil {
		return path, true
	} else if errors.Is(err, os.ErrNotExist) {
		return path, false
	}
	// If the marker path exists but cannot be inspected, keep the surrounding home
	// on --skip-docker rather than deleting the only host-side breadcrumb for a
	// Docker install the user explicitly kept.
	return path, true
}

func planDockerRuntimeMarkersForUninstall(home string) uninstallAction {
	target := dockerUninstallTargetForHome(home)
	paths, warnings := dockerRuntimeMarkersForUninstall(home, target.Target)
	warnings = append(warnings, target.Warnings...)
	return planDockerRuntimeMarkersFromScan(paths, warnings)
}

func planDockerRuntimeMarkersFromScan(paths []string, warnings []string) uninstallAction {
	action := uninstallAction{Name: "remove_docker_runtime_markers", Status: "skipped", Message: "no matching Docker runtime markers found"}
	if len(paths) > 0 {
		action.Status = "planned"
		action.Paths = paths
		action.Message = ""
	}
	if len(warnings) > 0 {
		action.Status = "warning"
		action.Error = strings.Join(warnings, "; ")
		if len(paths) == 0 {
			action.Message = "could not inspect Docker runtime markers"
		}
	}
	return action
}

func removeDockerRuntimeMarkersForUninstall(paths []string, warnings []string) uninstallAction {
	action := uninstallAction{Name: "remove_docker_runtime_markers", Status: "skipped", Message: "no matching Docker runtime markers found"}
	var removed []string
	for _, path := range paths {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			warnings = append(warnings, path+": "+err.Error())
			continue
		}
		removed = append(removed, path)
	}
	if len(removed) > 0 {
		action.Status = "removed"
		action.Paths = removed
		action.Message = ""
	}
	if len(warnings) > 0 {
		action.Status = "warning"
		action.Error = strings.Join(warnings, "; ")
		if len(removed) == 0 {
			action.Message = "could not inspect or remove Docker runtime markers"
		}
	}
	return action
}

func planDockerProjectedProfilesForUninstall(markerPaths []string, target dockerRuntimeTarget) uninstallAction {
	action := uninstallAction{Name: "remove_docker_projected_profiles", Status: "skipped", Message: "no projected Docker agent profiles found"}
	var removePaths []string
	var rewriteManifests []string
	var warnings []string
	seenManifests := map[string]bool{}
	for _, markerPath := range markerPaths {
		home := dockerRuntimeMarkerHomeFromPath(markerPath)
		if home == "" {
			continue
		}
		paths, err := commentbus.ResolvePaths(home)
		if err != nil {
			warnings = append(warnings, home+": "+err.Error())
			continue
		}
		marker, ok, err := readDockerRuntimeInstallMarker(paths)
		if err != nil {
			warnings = append(warnings, dockerRuntimeInstallMarkerPath(paths)+": "+err.Error())
			continue
		}
		if !ok || !dockerRuntimeMarkerMatchesUninstallTarget(marker, target) {
			continue
		}
		agentsDir := dockerProjectedAgentsDir(paths, marker)
		manifestPath := dockerProjectedManifestPathForDir(agentsDir)
		manifestKey := filepath.Clean(manifestPath)
		if seenManifests[manifestKey] {
			continue
		}
		seenManifests[manifestKey] = true
		file, err := openDockerRuntimeHostFileUnderRoot(agentsDir, manifestPath, "projected agent manifest")
		if err != nil {
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			warnings = append(warnings, manifestPath+": "+err.Error())
			continue
		}
		data, readErr := io.ReadAll(file)
		closeErr := file.Close()
		if readErr != nil {
			warnings = append(warnings, manifestPath+": "+readErr.Error())
			continue
		}
		if closeErr != nil {
			warnings = append(warnings, manifestPath+": "+closeErr.Error())
			continue
		}
		var manifest dockerProjectedManifest
		if err := json.Unmarshal(data, &manifest); err != nil {
			warnings = append(warnings, manifestPath+": "+err.Error())
			continue
		}
		manifestClean := true
		kept := make([]string, 0, len(manifest.Files))
		changed := false
		for _, name := range manifest.Files {
			if !safeProjectedAgentFilename(name) {
				warnings = append(warnings, manifestPath+": refusing unsafe projected filename "+name)
				manifestClean = false
				kept = append(kept, name)
				continue
			}
			profilePath := filepath.Join(agentsDir, name)
			exists, matches, err := dockerProjectedProfileMatchesTarget(agentsDir, profilePath, target)
			if err != nil {
				warnings = append(warnings, profilePath+": "+err.Error())
				manifestClean = false
				kept = append(kept, name)
				continue
			}
			if !exists {
				changed = true
				continue
			}
			if !matches {
				kept = append(kept, name)
				continue
			}
			removePaths = append(removePaths, profilePath)
			changed = true
		}
		if !manifestClean {
			continue
		}
		if changed {
			if len(kept) == 0 {
				removePaths = append(removePaths, manifestPath)
			} else {
				rewriteManifests = append(rewriteManifests, manifestPath)
			}
		}
	}
	if len(removePaths) > 0 || len(rewriteManifests) > 0 {
		action.Status = "planned"
		action.Paths = removePaths
		action.Message = ""
		if len(rewriteManifests) > 0 {
			action.Detail = map[string]any{"rewrite_manifests": rewriteManifests}
		}
	}
	if len(warnings) > 0 {
		action.Status = "warning"
		action.Error = strings.Join(warnings, "; ")
		if len(removePaths) == 0 && len(rewriteManifests) == 0 {
			action.Message = "could not inspect projected Docker agent profiles"
		}
	}
	return action
}

func removeDockerProjectedProfilesForUninstall(markerPaths []string, target dockerRuntimeTarget) uninstallAction {
	action := uninstallAction{Name: "remove_docker_projected_profiles", Status: "skipped", Message: "no projected Docker agent profiles found"}
	var removed []string
	var warnings []string
	seenManifests := map[string]bool{}
	for _, markerPath := range markerPaths {
		home := dockerRuntimeMarkerHomeFromPath(markerPath)
		if home == "" {
			continue
		}
		paths, err := commentbus.ResolvePaths(home)
		if err != nil {
			warnings = append(warnings, home+": "+err.Error())
			continue
		}
		marker, ok, err := readDockerRuntimeInstallMarker(paths)
		if err != nil {
			warnings = append(warnings, dockerRuntimeInstallMarkerPath(paths)+": "+err.Error())
			continue
		}
		if !ok || !dockerRuntimeMarkerMatchesUninstallTarget(marker, target) {
			continue
		}
		agentsDir := dockerProjectedAgentsDir(paths, marker)
		manifestPath := dockerProjectedManifestPathForDir(agentsDir)
		manifestKey := filepath.Clean(manifestPath)
		if seenManifests[manifestKey] {
			continue
		}
		seenManifests[manifestKey] = true
		file, err := openDockerRuntimeHostFileUnderRoot(agentsDir, manifestPath, "projected agent manifest")
		if err != nil {
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			warnings = append(warnings, manifestPath+": "+err.Error())
			continue
		}
		data, readErr := io.ReadAll(file)
		closeErr := file.Close()
		if readErr != nil {
			warnings = append(warnings, manifestPath+": "+readErr.Error())
			continue
		}
		if closeErr != nil {
			warnings = append(warnings, manifestPath+": "+closeErr.Error())
			continue
		}
		var manifest dockerProjectedManifest
		if err := json.Unmarshal(data, &manifest); err != nil {
			warnings = append(warnings, manifestPath+": "+err.Error())
			continue
		}
		manifestClean := true
		kept := make([]string, 0, len(manifest.Files))
		changed := false
		for _, name := range manifest.Files {
			if !safeProjectedAgentFilename(name) {
				warnings = append(warnings, manifestPath+": refusing unsafe projected filename "+name)
				manifestClean = false
				kept = append(kept, name)
				continue
			}
			profilePath := filepath.Join(agentsDir, name)
			exists, matches, err := dockerProjectedProfileMatchesTarget(agentsDir, profilePath, target)
			if err != nil {
				warnings = append(warnings, profilePath+": "+err.Error())
				manifestClean = false
				kept = append(kept, name)
				continue
			}
			if !exists {
				changed = true
				continue
			}
			if !matches {
				kept = append(kept, name)
				continue
			}
			if err := os.Remove(profilePath); err != nil && !errors.Is(err, os.ErrNotExist) {
				warnings = append(warnings, profilePath+": "+err.Error())
				manifestClean = false
				kept = append(kept, name)
				continue
			}
			if exists {
				removed = append(removed, profilePath)
			}
			changed = true
		}
		if !manifestClean {
			continue
		}
		if changed {
			if len(kept) == 0 {
				if err := os.Remove(manifestPath); err != nil && !errors.Is(err, os.ErrNotExist) {
					warnings = append(warnings, manifestPath+": "+err.Error())
					continue
				}
				removed = append(removed, manifestPath)
			} else if err := writeDockerProjectedManifestFile(manifestPath, kept); err != nil {
				warnings = append(warnings, manifestPath+": "+err.Error())
				continue
			}
		}
	}
	if len(removed) > 0 {
		action.Status = "removed"
		action.Paths = removed
		action.Message = ""
	}
	if len(warnings) > 0 {
		action.Status = "warning"
		action.Error = strings.Join(warnings, "; ")
		if len(removed) == 0 {
			action.Message = "could not remove projected Docker agent profiles"
		}
	}
	return action
}

type dockerProjectedManifest struct {
	Files []string `json:"files"`
}

func dockerProjectedProfileMatchesTarget(root string, profilePath string, target dockerRuntimeTarget) (bool, bool, error) {
	file, err := openDockerRuntimeHostFileUnderRoot(root, profilePath, "projected agent profile")
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return false, false, nil
		}
		return true, false, err
	}
	defer func() { _ = file.Close() }()
	data, err := io.ReadAll(file)
	if err != nil {
		return true, false, err
	}
	var profile struct {
		BaseURL string `json:"base_url"`
	}
	if err := json.Unmarshal(data, &profile); err != nil {
		return true, false, err
	}
	base := strings.TrimRight(strings.TrimSpace(profile.BaseURL), "/")
	if base == "" || target.BaseURL == "" {
		return true, false, nil
	}
	return true, sameBusPairBaseURL(base, target.BaseURL), nil
}

func writeDockerProjectedManifestFile(path string, files []string) error {
	sort.Strings(files)
	data, err := json.MarshalIndent(dockerProjectedManifest{Files: files}, "", "  ")
	if err != nil {
		return err
	}
	return commentbus.WritePrivateFileAtomicExistingDir(path, append(data, '\n'), 0o600)
}

func dockerRuntimeMarkerHomeFromPath(markerPath string) string {
	if filepath.Base(markerPath) != dockerRuntimeInstallMarker {
		return ""
	}
	busDir := filepath.Dir(markerPath)
	if filepath.Base(busDir) != "bus" {
		return ""
	}
	return filepath.Dir(busDir)
}

func dockerProjectedManifestPath(paths commentbus.Paths) string {
	return dockerProjectedManifestPathForDir(filepath.Join(paths.Home, "agents"))
}

func dockerProjectedAgentsDir(paths commentbus.Paths, marker dockerRuntimeTarget) string {
	if marker.ProjectedAgentsDir != "" {
		return marker.ProjectedAgentsDir
	}
	return filepath.Join(paths.Home, "agents")
}

func dockerProjectedManifestPathForDir(agentsDir string) string {
	return filepath.Join(agentsDir, ".comment-agent-projected.manifest")
}

func safeProjectedAgentFilename(name string) bool {
	return name != "" &&
		filepath.Base(name) == name &&
		!strings.ContainsAny(name, `/\`) &&
		strings.HasSuffix(name, ".json") &&
		name != ".json" &&
		name != ".comment-agent-projected.manifest"
}

func skipDockerRuntimeMarkersForUninstall(message string) uninstallAction {
	return uninstallAction{Name: "remove_docker_runtime_markers", Status: "skipped", Message: message}
}

// revokeDockerDaemonEarly performs ONLY the non-destructive Docker daemon
// self-revoke — read the token out of the state volume, revoke it, and clear the
// now-dead pairing state — without removing any container/volume/image. It runs
// before the abort-prone host steps so a Docker pairing is revoked even if
// uninstall later aborts, while the destructive artifact teardown
// (removeDockerArtifactsForUninstall) stays at its normal late position and only
// runs when uninstall completes. Silent when Docker is absent or the engine is
// unreachable — the later artifact step reports those.
func revokeDockerDaemonEarly(ctx context.Context, result *uninstallResult, target dockerUninstallTarget) {
	dockerBin, err := uninstallLookPath("docker")
	if err != nil {
		return
	}
	artifacts, err := listDockerAgentArtifacts(ctx, dockerBin, target.Slug, target.Exact)
	if err != nil {
		return
	}
	if dockerStateVolume(artifacts) != "" {
		appendUninstallAction(result, revokeDockerDaemonForUninstall(ctx, dockerBin, artifacts, result.Home))
	}
}

// dockerStateVolume returns the selected origin's comment-agent-state-<slug>
// volume — the one mounted at /state that holds bus/daemon-auth.json — or "" when
// none is present.
func dockerStateVolume(artifacts dockerAgentArtifacts) string {
	prefix := dockerAgentResourcePrefix + "state-"
	for _, vol := range artifacts.Volumes {
		if strings.HasPrefix(vol, prefix) {
			return vol
		}
	}
	return ""
}

// dockerDaemonReadImages is the ordered list of images to TRY when mounting the
// state volume to read+clear daemon-auth.json: the ref the container actually used
// when known, else the env-aware default list for the home being uninstalled. We
// try the WHOLE list (not just the first) because a staging install may have fallen
// back to the production image — if the staging image isn't present/published,
// trying only it would fail the revoke and the volume would still be deleted,
// orphaning the server-side paired daemon. The first image whose `docker run`
// succeeds is used.
func dockerDaemonReadImages(artifacts dockerAgentArtifacts, home string) []string {
	if len(artifacts.Images) > 0 && strings.TrimSpace(artifacts.Images[0]) != "" {
		return []string{artifacts.Images[0]}
	}
	return fallbackAgentImageRefs(home)
}

// dockerNoDaemonAuthSentinel is printed by the read probe when
// /state/bus/daemon-auth.json does not exist, so a never-paired volume (a clean
// skip) is distinguished from a real pairing. The probe runs as root (--user 0)
// so file ownership/permissions can never make a present token look absent (a
// leftover volume written by a different image UID is still read and revoked).
const dockerNoDaemonAuthSentinel = "__comment_no_daemon_auth__"

// revokeDockerDaemonForUninstall reads the daemon token out of the Docker state
// volume and revokes it server-side BEFORE that volume is deleted. Docker-mode
// installs keep the pairing inside comment-agent-state-<slug> at
// /state/bus/daemon-auth.json — NOT the host paths.Home the host-side
// unpair_daemon step reads — so without this the volume teardown would delete the
// only daemon token without ever calling /daemon/self-revoke, leaving the
// computer paired and its daemon-minted credentials live server-side. The read
// mirrors the install script's own probe (dockerAgentInstallLines in
// packages/shared/src/agent-docs.ts), reading the file out of the volume via a
// throwaway container; `--entrypoint sh` is required because the agent image
// entrypoint forwards argv to `comment`. A present-but-unparseable file is a
// warning (a real-but-unusable pairing we can't revoke from here), distinct from
// an absent file (never paired → clean skip). Best-effort: any failure is a
// warning that points at the web app, never an error, so a flaky engine can't
// fail uninstall.
func revokeDockerDaemonForUninstall(ctx context.Context, dockerBin string, artifacts dockerAgentArtifacts, home string) uninstallAction {
	stateVol := dockerStateVolume(artifacts)
	if stateVol == "" {
		return uninstallAction{Name: "unpair_docker_daemon", Status: "skipped", Message: "no Docker state volume for this origin"}
	}
	// Read as root (--user 0) so a token owned by a different image UID is still
	// read (and revoked), never silently dropped. A missing file prints the
	// sentinel → never paired → skip; a present file is always readable here. Try
	// each candidate image until one runs; `image` is then reused for the clears.
	var out []byte
	var err error
	var image string
	for _, candidate := range dockerDaemonReadImages(artifacts, home) {
		out, err = runUninstallCommand(ctx, 60*time.Second, dockerBin,
			"run", "--rm", "--user", "0", "--entrypoint", "sh",
			"-v", stateVol+":/state", candidate,
			"-c", "if [ -f /state/bus/daemon-auth.json ]; then cat /state/bus/daemon-auth.json; else echo "+dockerNoDaemonAuthSentinel+"; fi")
		if err == nil {
			image = candidate
			break
		}
	}
	if err != nil {
		return uninstallAction{
			Name:    "unpair_docker_daemon",
			Status:  "warning",
			Path:    stateVol,
			Message: "could not read the Docker daemon token to revoke it server-side. If this computer still appears under Settings -> Paired computers, revoke it there.",
			Error:   err.Error(),
		}
	}
	trimmed := strings.TrimSpace(string(out))
	if trimmed == dockerNoDaemonAuthSentinel {
		return uninstallAction{Name: "unpair_docker_daemon", Status: "skipped", Path: stateVol, Message: "no daemon pairing in the Docker state volume"}
	}
	var auth commentbus.DaemonAuth
	if jsonErr := json.Unmarshal([]byte(trimmed), &auth); jsonErr != nil || strings.TrimSpace(auth.Token) == "" {
		// A real file we can't use: the daemon may still be live server-side, so
		// drop just the token (so a surviving volume doesn't look paired) and
		// surface manual-revoke guidance, without touching profiles (their
		// credentials may still be valid).
		clearDockerVolumePaths(ctx, dockerBin, stateVol, image, dockerDaemonAuthPath)
		return uninstallAction{
			Name:    "unpair_docker_daemon",
			Status:  "warning",
			Path:    stateVol,
			Message: "the Docker state volume's daemon-auth.json could not be parsed, so this daemon could not be revoked from here. If this computer still appears under Settings -> Paired computers, revoke it there.",
		}
	}
	// A 401/403 is AMBIGUOUS (already-revoked vs stale token), so it must not
	// claim success — mirror the host-side unpair handling. On every non-confirmed
	// path drop just the (now-dead or rejected) token from the volume so a
	// surviving volume can't wedge a reinstall ("paired" probe is `test -f
	// daemon-auth.json`), but leave profiles alone since their credentials may
	// still be live.
	switch status, revokeErr := busUnpairSelfRevoke(ctx, auth); {
	case revokeErr != nil:
		clearDockerVolumePaths(ctx, dockerBin, stateVol, image, dockerDaemonAuthPath)
		return uninstallAction{
			Name:    "unpair_docker_daemon",
			Status:  "warning",
			Error:   revokeErr.Error(),
			Message: "could not reach the server to revoke this daemon. Revoke it under Settings -> Paired computers.",
		}
	case status == http.StatusOK:
		detail := map[string]any{"daemon_id": auth.DaemonID}
		// Clear the now-dead pairing + enrollment state from the volume, mirroring
		// the host path's DeleteDaemonAuth + enrolled-profile cleanup, so a volume
		// that survives a partial Docker teardown can't wedge a reinstall.
		// Best-effort: a clear failure is recorded, not fatal.
		if clrErr := clearDockerVolumePaths(ctx, dockerBin, stateVol, image, dockerConfirmedRevokeClearPaths...); clrErr != nil {
			detail["pairing_state_clear_error"] = clrErr.Error()
		}
		return uninstallAction{Name: "unpair_docker_daemon", Status: "removed", Detail: detail}
	case status == http.StatusUnauthorized || status == http.StatusForbidden:
		clearDockerVolumePaths(ctx, dockerBin, stateVol, image, dockerDaemonAuthPath)
		return uninstallAction{
			Name:    "unpair_docker_daemon",
			Status:  "warning",
			Message: "the server rejected this daemon token, so revocation could NOT be confirmed (the token may be stale, or the daemon may already be revoked). If this computer still appears under Settings -> Paired computers, revoke it there.",
		}
	default:
		clearDockerVolumePaths(ctx, dockerBin, stateVol, image, dockerDaemonAuthPath)
		return uninstallAction{
			Name:    "unpair_docker_daemon",
			Status:  "warning",
			Message: fmt.Sprintf("server-side revocation failed (HTTP %d). Revoke it under Settings -> Paired computers.", status),
		}
	}
}

// In-container paths under the state volume (mounted at /state, COMMENT_IO_HOME).
const dockerDaemonAuthPath = "/state/bus/daemon-auth.json"

// dockerConfirmedRevokeClearPaths is everything to wipe from the state volume
// after a CONFIRMED self-revoke killed the daemon's credentials: the token, the
// enrollment journal, the enrollment-installed agent profiles, AND the Botlets
// home (the agent image sets BOTLETS_HOME=/state/botlets, whose registry points at
// those now-revoked profiles — left behind, a reinstall reusing a surviving volume
// reloads them as already-installed / MISSING_CREDENTIAL_PROFILE). This is the
// Docker equivalent of the host DeleteDaemonAuth + busUnpairCleanupEnrolledProfiles.
// The volume is normally deleted right after; this only matters if a later Docker
// step warns and the volume survives. Per-origin volume, so everything in it
// belongs to this revoked daemon — wholesale clearing is safe.
var dockerConfirmedRevokeClearPaths = []string{
	dockerDaemonAuthPath,
	"/state/bus/enroll-journal.json",
	"/state/agents",
	"/state/botlets",
}

// clearDockerVolumePaths removes the given fixed in-volume paths via a throwaway
// root container (--user 0 so a foreign-UID volume is still writable;
// `--entrypoint sh -c` because the agent image entrypoint forwards argv to
// `comment`). targets are fixed constants, never user input. Best-effort.
func clearDockerVolumePaths(ctx context.Context, dockerBin, stateVol, image string, targets ...string) error {
	if len(targets) == 0 {
		return nil
	}
	_, err := runUninstallCommand(ctx, 30*time.Second, dockerBin,
		"run", "--rm", "--user", "0", "--entrypoint", "sh",
		"-v", stateVol+":/state", image,
		"-c", "rm -rf "+strings.Join(targets, " "))
	return err
}

// appendDockerOtherOriginsAction reports comment-agent containers AND volumes left
// in place (belonging to other origins, or — when ambiguous — every present
// resource), so a multi-origin daemon's untouched, credential-bearing leftovers
// are visible rather than silently skipped.
func appendDockerOtherOriginsAction(result *uninstallResult, artifacts dockerAgentArtifacts) {
	if len(artifacts.OtherContainers) == 0 && len(artifacts.OtherVolumes) == 0 {
		return
	}
	paths := append(append([]string{}, artifacts.OtherContainers...), artifacts.OtherVolumes...)
	appendUninstallAction(result, uninstallAction{
		Name:    "docker_other_origins",
		Status:  "skipped",
		Paths:   paths,
		Detail:  map[string]any{"containers": artifacts.OtherContainers, "volumes": artifacts.OtherVolumes},
		Message: "left other Comment.io origins' Docker agent containers/volumes (daemon pairing + agent credentials) in place; this uninstall targets only its own origin. Remove them deliberately with: docker rm -f <container> ; docker volume rm <volume>",
	})
}

// dockerContainersSkipMessage explains an empty container removal: ambiguous
// multi-origin, this origin's container already gone (volumes still cleaned), or
// nothing present.
func dockerContainersSkipMessage(artifacts dockerAgentArtifacts) string {
	switch {
	case artifacts.Ambiguous:
		return "multiple origins' agents present and none matches the active environment; none removed (see docker_other_origins)"
	case len(artifacts.Volumes) > 0:
		return "this origin's agent container was already removed; cleaned up its leftover volumes"
	case artifacts.AnyContainer:
		return "no agent container for this origin (only other origins' agents are present)"
	default:
		return "no comment-agent containers found"
	}
}

// dockerVolumesSkipMessage explains an empty volume removal, pointing at the
// other-origins report when credential-bearing leftovers exist.
func dockerVolumesSkipMessage(artifacts dockerAgentArtifacts) string {
	if len(artifacts.OtherVolumes) > 0 {
		return "no volumes for this origin; other origins' volumes left in place (see docker_other_origins)"
	}
	return "no comment-agent volumes found"
}

// addDockerPlanActions records what removeDockerArtifactsForUninstall would do, so
// `--dry-run` lists the containers/volumes/image without touching them.
func addDockerPlanActions(result *uninstallResult, options uninstallOptions) bool {
	dockerBin, err := uninstallLookPath("docker")
	if err != nil {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_containers", Status: "skipped", Message: "docker not found on PATH"})
		return false
	}
	target := dockerUninstallTargetForHome(result.Home)
	if target.Blocked {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_containers", Status: "warning", Message: "Docker runtime marker could not be trusted; Docker artifacts would be left in place", Error: strings.Join(target.Warnings, "; ")})
		return false
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	artifacts, err := listDockerAgentArtifacts(ctx, dockerBin, target.Slug, target.Exact)
	if err != nil {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_containers", Status: "skipped", Message: "could not query Docker (is the engine running?)", Error: err.Error()})
		return false
	}
	if dockerStateVolume(artifacts) != "" {
		appendUninstallAction(result, uninstallAction{Name: "unpair_docker_daemon", Status: "planned", Path: dockerStateVolume(artifacts)})
	}
	if len(artifacts.Containers) == 0 {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_containers", Status: "skipped", Message: dockerContainersSkipMessage(artifacts)})
	} else {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_containers", Status: "planned", Paths: artifacts.Containers})
	}
	if len(artifacts.Volumes) == 0 {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_volumes", Status: "skipped", Message: dockerVolumesSkipMessage(artifacts)})
	} else {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_volumes", Status: "planned", Paths: artifacts.Volumes})
	}
	if images := dockerImagesToRemove(artifacts, result.Home); options.RemoveImage && len(images) > 0 {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_image", Status: "planned", Paths: images})
	}
	appendDockerOtherOriginsAction(result, artifacts)
	return !artifacts.Ambiguous
}

// removeDockerArtifactsForUninstall removes the comment-agent containers and named
// volumes (and, with --remove-image, the pulled image). Docker problems surface as
// "warning" rather than "error" so a flaky/stopped engine never fails the
// host-side uninstall — mirroring reclaimSocketForUninstall.
func removeDockerArtifactsForUninstall(ctx context.Context, options uninstallOptions, result *uninstallResult, target dockerUninstallTarget) bool {
	dockerBin, err := uninstallLookPath("docker")
	if err != nil {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_containers", Status: "skipped", Message: "docker not found on PATH"})
		return false
	}
	artifacts, err := listDockerAgentArtifacts(ctx, dockerBin, target.Slug, target.Exact)
	if err != nil {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_containers", Status: "warning", Message: "could not query Docker (is the engine running?)", Error: err.Error()})
		return false
	}
	cleanupSafe := !artifacts.Ambiguous

	// Containers first: `docker volume rm` refuses a volume still attached to a
	// container, so the volume step depends on these being gone.
	if len(artifacts.Containers) == 0 {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_containers", Status: "skipped", Message: dockerContainersSkipMessage(artifacts)})
	} else {
		var failures []string
		for _, name := range artifacts.Containers {
			if _, err := runUninstallCommand(ctx, 30*time.Second, dockerBin, "rm", "-f", name); err != nil {
				failures = append(failures, name+": "+err.Error())
			}
		}
		action := uninstallAction{Name: "remove_docker_containers", Status: "removed", Paths: artifacts.Containers}
		if len(failures) > 0 {
			action.Status = "warning"
			action.Error = strings.Join(failures, "; ")
			cleanupSafe = false
		}
		appendUninstallAction(result, action)
	}

	if len(artifacts.Volumes) == 0 {
		appendUninstallAction(result, uninstallAction{Name: "remove_docker_volumes", Status: "skipped", Message: dockerVolumesSkipMessage(artifacts)})
	} else {
		var failures []string
		for _, name := range artifacts.Volumes {
			if _, err := runUninstallCommand(ctx, 30*time.Second, dockerBin, "volume", "rm", name); err != nil {
				failures = append(failures, name+": "+err.Error())
			}
		}
		action := uninstallAction{Name: "remove_docker_volumes", Status: "removed", Paths: artifacts.Volumes}
		if len(failures) > 0 {
			action.Status = "warning"
			action.Error = strings.Join(failures, "; ")
			cleanupSafe = false
		}
		appendUninstallAction(result, action)
	}

	// Image last: rmi only succeeds once no container references it. We drop the
	// image the target container actually used (captured before rm above).
	if images := dockerImagesToRemove(artifacts, result.Home); options.RemoveImage && len(images) > 0 {
		var failures []string
		for _, image := range images {
			out, err := runUninstallCommand(ctx, 60*time.Second, dockerBin, "rmi", image)
			if err == nil {
				continue
			}
			// A tag that isn't present locally is already in the desired (absent)
			// state — expected for the both-defaults fallback, where a machine
			// normally has only one of the two tags. Not a failure.
			if strings.Contains(string(out), "No such image") {
				continue
			}
			failures = append(failures, image+": "+err.Error())
		}
		action := uninstallAction{Name: "remove_docker_image", Status: "removed", Paths: images}
		if len(failures) > 0 {
			action.Status = "warning"
			action.Error = strings.Join(failures, "; ")
		}
		appendUninstallAction(result, action)
	}

	appendDockerOtherOriginsAction(result, artifacts)
	return cleanupSafe
}
